<a href="https://colab.research.google.com/github/alexsanderthorne/smartSystems/blob/main/salesman_ga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#[1] Importando pacotes e módulos

import random
import numpy

from deap import algorithms
from deap import base
from deap import creator
from deap import tools

In [12]:
#[2] Geração do grafo para o problema do caixeiro

# função graphTSP(numCities, minDist, maxDist)
# parâmetros: 
#   numCities: número de cities
#   minDist: menor valor de distância
#   maxDist: maior valor de distância
# retorno:
#   cities: grafo de cidades (Matriz numCities X numCities). As distância 
#   entre duas cidades são determinadas aleatoriamente entre minDist e maxDist
def graphTSP(numCities, minDist, maxDist):
  cities = numpy.zeros((numCities, numCities), dtype = int)
  for i in range(numCities):
    for j in range(numCities):
      if (j>i):
        cities[i, j] = random.randint(minDist, maxDist)
      elif (j<i):
        cities[i, j] = cities[j, i]
  return cities

numCities = 5     #  Número de cidade inicial

while(True):
  numCities = int(input('Digite o número de cidades: '))
  if (numCities > 4):
    break
  else:
    print('O número de cidades deve ser maior que 4!')

cities = graphTSP(numCities, 10, 100)
print('Grafo:\n', cities)

Grafo:
 [[ 0 88 94 44 32 49]
 [88  0 40 92 92 23]
 [94 40  0 17 92 54]
 [44 92 17  0 89 40]
 [32 92 92 89  0 42]
 [49 23 54 40 42  0]]


In [13]:
#[3] Definição da Geração dos Indivíduos

creator.create("FitnessMin", base.Fitness, weights=(-1.0,)) # minimizar = peso negativo 
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
# gerador de parâmetros 
toolbox.register("attr_int", random.randint, 0, numCities-1)

# define como os indivíduos/população é gerada
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_int, numCities)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

In [14]:
#[4] Função para a avaliação da aptidão

# Função evalRoute(individual)
# parâmetros:
#   individual: uma rota
# retorno:
#   (cost, ): tupla contendo apenas o custo da rota (cost).
#             * precisa ser uma tupla devido a exigências do pacote DEAP 
def evalRoute(individual):
  cost = 0
  for i in range(1, len(individual)):
    if (individual.count(individual[i])>1):
      cost = cost + 1000000 # penalidade por repetir cidade
    cost = cost + cities[individual[i-1], individual[i]]        
  cost = cost + cities[individual[i],individual[0]]
  return (cost,)

In [15]:
#[5] Processamento do Algoritmo Genético

# Definindo avaliação de aptidão, seleção, cruzamento e mutação 
toolbox.register("evaluate", evalRoute)
toolbox.register("select", tools.selTournament, tournsize=3) # seleção por torneio
toolbox.register("mate", tools.cxOnePoint) # um ponto de cruzamento
toolbox.register("mutate", tools.mutUniformInt, low=0, up=numCities-1, indpb=0.05)

def main()
  print('Execução do algoritmo genético:')

  # random.seed(64)
  NGEN = 100     # número de gerações
  MU = 50        # tamanho da população
  LAMBDA = 100   # número de filhos gerados
  CXPB = 0.7     # probabilidade de cruzamento
  MUTPB = 0.3    # probabilidade de mutação
  
  pop = toolbox.population(n=MU)
  hof = tools.ParetoFront()
  stats = tools.Statistics(lambda ind: ind.fitness.values)
  stats.register("avg", numpy.mean, axis=0)
  stats.register("std", numpy.std, axis=0)
  stats.register("min", numpy.min, axis=0)
  stats.register("max", numpy.max, axis=0)
  
  algorithms.eaMuPlusLambda(pop, toolbox, MU, LAMBDA, CXPB, MUTPB, NGEN, stats,
                            halloffame=hof)
      
  print('\nRota:', hof[0],'\nCusto:', evalRoute(hof[0])[0])
  return pop, stats, hof
                 
if __name__ == "__main__":
    main()

SyntaxError: invalid syntax (3183069625.py, line 9)